// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: ysp.proto

package ysp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cn) Reset() {
	*x = Cn{}
	mi := &file_ysp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cn) ProtoMessage() {}

func (x *Cn) ProtoReflect() protoreflect.Message {
	mi := &file_ysp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cn.ProtoReflect.Descriptor instead.
func (*Cn) Descriptor() ([]byte, []int) {
	return file_ysp_proto_rawDescGZIP(), []int{0}
}

type CnYangshipin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CnYangshipin) Reset() {
	*x = CnYangshipin{}
	mi := &file_ysp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CnYangshipin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CnYangshipin) ProtoMessage() {}

func (x *CnYangshipin) ProtoReflect() protoreflect.Message {
	mi := &file_ysp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CnYangshipin.ProtoReflect.Descriptor instead.
func (*CnYangshipin) Descriptor() ([]byte, []int) {
	return file_ysp_proto_rawDescGZIP(), []int{0, 0}
}

type CnYangshipinOmstv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CnYangshipinOmstv) Reset() {
	*x = CnYangshipinOmstv{}
	mi := &file_ysp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CnYangshipinOmstv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CnYangshipinOmstv) ProtoMessage() {}

func (x *CnYangshipinOmstv) ProtoReflect() protoreflect.Message {
	mi := &file_ysp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CnYangshipinOmstv.ProtoReflect.Descriptor instead.
func (*CnYangshipinOmstv) Descriptor() ([]byte, []int) {
	return file_ysp_proto_rawDescGZIP(), []int{0, 0, 0}
}

type CnYangshipinOmstvCommon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CnYangshipinOmstvCommon) Reset() {
	*x = CnYangshipinOmstvCommon{}
	mi := &file_ysp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CnYangshipinOmstvCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CnYangshipinOmstvCommon) ProtoMessage() {}

func (x *CnYangshipinOmstvCommon) ProtoReflect() protoreflect.Message {
	mi := &file_ysp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CnYangshipinOmstvCommon.ProtoReflect.Descriptor instead.
func (*CnYangshipinOmstvCommon) Descriptor() ([]byte, []int) {
	return file_ysp_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type CnYangshipinOmstvCommonProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CnYangshipinOmstvCommonProto) Reset() {
	*x = CnYangshipinOmstvCommonProto{}
	mi := &file_ysp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CnYangshipinOmstvCommonProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CnYangshipinOmstvCommonProto) ProtoMessage() {}

func (x *CnYangshipinOmstvCommonProto) ProtoReflect() protoreflect.Message {
	mi := &file_ysp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CnYangshipinOmstvCommonProto.ProtoReflect.Descriptor instead.
func (*CnYangshipinOmstvCommonProto) Descriptor() ([]byte, []int) {
	return file_ysp_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0}
}

type CnYangshipinOmstvCommonProtoEpgProgramModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModel) Reset() {
	*x = CnYangshipinOmstvCommonProtoEpgProgramModel{}
	mi := &file_ysp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CnYangshipinOmstvCommonProtoEpgProgramModel) ProtoMessage() {}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModel) ProtoReflect() protoreflect.Message {
	mi := &file_ysp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CnYangshipinOmstvCommonProtoEpgProgramModel.ProtoReflect.Descriptor instead.
func (*CnYangshipinOmstvCommonProtoEpgProgramModel) Descriptor() ([]byte, []int) {
	return file_ysp_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0, 0}
}

type CnYangshipinOmstvCommonProtoEpgProgramModel_Response struct {
	state         protoimpl.MessageState                                             `protogen:"open.v1"`
	Code          uint32                                                             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	DataList      []*CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program `protobuf:"bytes,2,rep,name=dataList,proto3" json:"dataList,omitempty"`
	Message       string                                                             `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	UpdateTime    uint64                                                             `protobuf:"varint,4,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModel_Response) Reset() {
	*x = CnYangshipinOmstvCommonProtoEpgProgramModel_Response{}
	mi := &file_ysp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModel_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CnYangshipinOmstvCommonProtoEpgProgramModel_Response) ProtoMessage() {}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModel_Response) ProtoReflect() protoreflect.Message {
	mi := &file_ysp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CnYangshipinOmstvCommonProtoEpgProgramModel_Response.ProtoReflect.Descriptor instead.
func (*CnYangshipinOmstvCommonProtoEpgProgramModel_Response) Descriptor() ([]byte, []int) {
	return file_ysp_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0, 0, 0}
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModel_Response) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModel_Response) GetDataList() []*CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program {
	if x != nil {
		return x.DataList
	}
	return nil
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModel_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModel_Response) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel) Reset() {
	*x = CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel{}
	mi := &file_ysp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel) ProtoMessage() {}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel) ProtoReflect() protoreflect.Message {
	mi := &file_ysp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel.ProtoReflect.Descriptor instead.
func (*CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel) Descriptor() ([]byte, []int) {
	return file_ysp_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0, 0, 1}
}

type CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProgramId           string                 `protobuf:"bytes,1,opt,name=programId,proto3" json:"programId,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	St                  uint64                 `protobuf:"varint,3,opt,name=st,proto3" json:"st,omitempty"`
	Et                  uint64                 `protobuf:"varint,4,opt,name=et,proto3" json:"et,omitempty"`
	StartTime           string                 `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime             string                 `protobuf:"bytes,6,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Duration            uint32                 `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	IsVip               bool                   `protobuf:"varint,8,opt,name=isVip,proto3" json:"isVip,omitempty"`
	CopyrightFlag       string                 `protobuf:"bytes,9,opt,name=copyrightFlag,proto3" json:"copyrightFlag,omitempty"`
	TimeShiftReviewFlag string                 `protobuf:"bytes,10,opt,name=timeShiftReviewFlag,proto3" json:"timeShiftReviewFlag,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) Reset() {
	*x = CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program{}
	mi := &file_ysp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) ProtoMessage() {}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) ProtoReflect() protoreflect.Message {
	mi := &file_ysp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program.ProtoReflect.Descriptor instead.
func (*CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) Descriptor() ([]byte, []int) {
	return file_ysp_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0, 0, 1, 0}
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) GetProgramId() string {
	if x != nil {
		return x.ProgramId
	}
	return ""
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) GetSt() uint64 {
	if x != nil {
		return x.St
	}
	return 0
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) GetEt() uint64 {
	if x != nil {
		return x.Et
	}
	return 0
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) GetIsVip() bool {
	if x != nil {
		return x.IsVip
	}
	return false
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) GetCopyrightFlag() string {
	if x != nil {
		return x.CopyrightFlag
	}
	return ""
}

func (x *CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program) GetTimeShiftReviewFlag() string {
	if x != nil {
		return x.TimeShiftReviewFlag
	}
	return ""
}

var File_ysp_proto protoreflect.FileDescriptor

const file_ysp_proto_rawDesc = "" +
	"\n" +
	"\tysp.proto\x12\x03ysp\"\xba\x04\n" +
	"\x02cn\x1a\xb3\x04\n" +
	"\n" +
	"yangshipin\x1a\xa4\x04\n" +
	"\x05omstv\x1a\x9a\x04\n" +
	"\x06common\x1a\x8f\x04\n" +
	"\x05proto\x1a\x85\x04\n" +
	"\x0fepgProgramModel\x1a\xc0\x01\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12f\n" +
	"\bdataList\x18\x02 \x03(\v2J.ysp.cn.yangshipin.omstv.common.proto.epgProgramModel.programModel.ProgramR\bdataList\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x04 \x01(\x04R\n" +
	"updateTime\x1a\xae\x02\n" +
	"\fprogramModel\x1a\x9d\x02\n" +
	"\aProgram\x12\x1c\n" +
	"\tprogramId\x18\x01 \x01(\tR\tprogramId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02st\x18\x03 \x01(\x04R\x02st\x12\x0e\n" +
	"\x02et\x18\x04 \x01(\x04R\x02et\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\tR\tstartTime\x12\x18\n" +
	"\aendTime\x18\x06 \x01(\tR\aendTime\x12\x1a\n" +
	"\bduration\x18\a \x01(\rR\bduration\x12\x14\n" +
	"\x05isVip\x18\b \x01(\bR\x05isVip\x12$\n" +
	"\rcopyrightFlag\x18\t \x01(\tR\rcopyrightFlag\x120\n" +
	"\x13timeShiftReviewFlag\x18\n" +
	" \x01(\tR\x13timeShiftReviewFlagB\aZ\x05./yspb\x06proto3"

var (
	file_ysp_proto_rawDescOnce sync.Once
	file_ysp_proto_rawDescData []byte
)

func file_ysp_proto_rawDescGZIP() []byte {
	file_ysp_proto_rawDescOnce.Do(func() {
		file_ysp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ysp_proto_rawDesc), len(file_ysp_proto_rawDesc)))
	})
	return file_ysp_proto_rawDescData
}

var file_ysp_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ysp_proto_goTypes = []any{
	(*Cn)(nil),                                                              // 0: ysp.cn
	(*CnYangshipin)(nil),                                                    // 1: ysp.cn.yangshipin
	(*CnYangshipinOmstv)(nil),                                               // 2: ysp.cn.yangshipin.omstv
	(*CnYangshipinOmstvCommon)(nil),                                         // 3: ysp.cn.yangshipin.omstv.common
	(*CnYangshipinOmstvCommonProto)(nil),                                    // 4: ysp.cn.yangshipin.omstv.common.proto
	(*CnYangshipinOmstvCommonProtoEpgProgramModel)(nil),                     // 5: ysp.cn.yangshipin.omstv.common.proto.epgProgramModel
	(*CnYangshipinOmstvCommonProtoEpgProgramModel_Response)(nil),            // 6: ysp.cn.yangshipin.omstv.common.proto.epgProgramModel.Response
	(*CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel)(nil),         // 7: ysp.cn.yangshipin.omstv.common.proto.epgProgramModel.programModel
	(*CnYangshipinOmstvCommonProtoEpgProgramModelProgramModel_Program)(nil), // 8: ysp.cn.yangshipin.omstv.common.proto.epgProgramModel.programModel.Program
}
var file_ysp_proto_depIdxs = []int32{
	8, // 0: ysp.cn.yangshipin.omstv.common.proto.epgProgramModel.Response.dataList:type_name -> ysp.cn.yangshipin.omstv.common.proto.epgProgramModel.programModel.Program
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ysp_proto_init() }
func file_ysp_proto_init() {
	if File_ysp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ysp_proto_rawDesc), len(file_ysp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ysp_proto_goTypes,
		DependencyIndexes: file_ysp_proto_depIdxs,
		MessageInfos:      file_ysp_proto_msgTypes,
	}.Build()
	File_ysp_proto = out.File
	file_ysp_proto_goTypes = nil
	file_ysp_proto_depIdxs = nil
}
